### ISSUE TITLE
Filtering seems to be give up after a few commas

### ISSUE THREAD

**Issue by dotnetCarpenter** [jonrohan/browserl.ist#98]
E.g. http://browserl.ist/?q=last+1+version%2C+not+IE+%3C+11%2C+%3E+0.2%25 should not show browsers with less than `0.2%` but QQ Browser1.2, Android Browser67, Baidu Browser7.12 are all `0%` usage browsers that **do** show up in the list.

On the other hand http://browserl.ist/?q=%3E+0.2%25 does hide `0%` usage browsers...

**Comment by jonrohan** [comment]
Those `0%` browsers are showing up because of the `last 1 version` query http://browserl.ist/?q=last+1+version

Checking with the cli version of https://github.com/browserslist/browserslist the browsers show up in the results. If you believe that they should filter out results under a certain number I suggest creating an issue with them https://github.com/browserslist/browserslist/issues/new

![image](https://user-images.githubusercontent.com/54012/43590696-785ea244-9626-11e8-93e7-d207ee6a4f2b.png)
